//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatEntidadFederativa
    {
        public CatEntidadFederativa()
        {
            this.Empleado = new HashSet<Empleado>();
        }
    
        public int Id { get; set; }
        public string Estado { get; set; }
    
        public virtual ICollection<Empleado> Empleado { get; set; }
    }
}
